export const getColumnsForRole = (role) => {
  const allColumns = [
    { field: "srNo", headerName: "Sr no" },
    // { field: "srNoOld", headerName: "Sr no Old" },
    { field: "natureOfWork", headerName: "Nature of Work" },
    { field: "region", headerName: "Region" },
    { field: "projectDescription", headerName: "Project Description" },
    { field: "vendorNo", headerName: "Vendor no" },
    { field: "vendorName", headerName: "Vendor Name" },
    { field: "gstNumber", headerName: "GST Number" },
    { field: "compliance206AB", headerName: "206AB Compliance" },
    { field: "panStatus", headerName: "PAN Status" },
    { field: "poCreated", headerName: "If PO created??" },
    { field: "poNo", headerName: "PO no" },
    { field: "poDate", headerName: "PO Dt" },
    { field: "poAmt", headerName: "PO Amt" },
    { field: "proformaInvNo", headerName: "Proforma Inv No" },
    { field: "proformaInvDate", headerName: "Proforma Inv Dt" },
    { field: "proformaInvAmt", headerName: "Proforma Inv Amt" },
    { field: "proformaInvRecdAtSite", headerName: "Proforma Inv Recd at site" },
    { field: "proformaInvRecdBy", headerName: "Proforma Inv Recd by" },
    { field: "taxInvNo", headerName: "Tax Inv no" },
    { field: "taxInvDate", headerName: "Tax Inv Dt" },
    { field: "currency", headerName: "Currency" },
    { field: "taxInvAmt", headerName: "Tax Inv Amt" },
    { field: "taxInvRecdAtSite", headerName: "Tax Inv Recd at site" },
    { field: "taxInvRecdBy", headerName: "Tax Inv Recd by" },
    { field: "department", headerName: "Department" },
    { field: "remarksBySiteTeam", headerName: "Remarks related to Inv" },
    { field: "attachments", headerName: "Attachment" },
    { field: "advanceDate", headerName: "Advance Dt" },
    { field: "advanceAmt", headerName: "Advance Amt" },
    { field: "advancePercentage", headerName: "Advance Percentage" },
    { field: "advRequestEnteredBy", headerName: "Adv request entered by" },
    { field: "qualityEngineer.dateGiven", headerName: "Dt given to Quality Engineer" },
    { field: "qualityEngineer.name", headerName: "Name of Quality Engineer" },
    { field: "qsInspection.dateGiven", headerName: "Dt given to QS for Inspection" },
    { field: "qsInspection.name", headerName: "Name of QS Inspection" },
    { field: "qsMeasurementCheck.dateGiven", headerName: "Dt Checked by QS with Measurement" },
    { field: "vendorFinalInv.dateGiven", headerName: "Dt given to vendor-Query/Final Inv" },
    { field: "vendorFinalInv.name", headerName: "Name-QS given to vendor" },
    { field: "qsCOP.dateGiven", headerName: "Dt Given to QS for COP" },
    { field: "qsCOP.name", headerName: "Name of QS COP" },
    { field: "copDetails.date", headerName: "COP Dt" },
    { field: "copDetails.amount", headerName: "COP Amt" },
    { field: "remarksByQSTeam", headerName: "Remarks by QS Team" },
    { field: "migoDetails.dateGiven", headerName: "Dt given for MIGO" },
    { field: "migoDetails.no", headerName: "MIGO no" },
    { field: "migoDetails.date", headerName: "MIGO Dt" },
    { field: "migoDetails.amount", headerName: "MIGO Amt" },
    { field: "migoDetails.doneBy", headerName: "MIGO done by" },
    { field: "invReturnedToSite", headerName: "Dt-Inv returned to Site office" },
    { field: "siteEngineer.dateGiven", headerName: "Dt given to Site Engineer" },
    { field: "siteEngineer.name", headerName: "Name of Site Engineer" },
    { field: "architect.dateGiven", headerName: "Dt given to Architect" },
    { field: "architect.name", headerName: "Name of Architect" },
    { field: "siteIncharge.dateGiven", headerName: "Dt given-Site Incharge" },
    { field: "siteIncharge.name", headerName: "Name of Site Incharge" },
    { field: "remarks", headerName: "Remarks at site" },
    { field: "siteOfficeDispatch.dateGiven", headerName : "Dt given to Site Office for dispatch" },
    { field: "siteOfficeDispatch.name", headerName: "Name of Site Office" },
    { field: "siteStatus", headerName: "Status" },
    { field: "pimoMumbai.dateGiven", headerName: "Dt dispatched to PIMO" },
    { field: "pimoMumbai.dateReceived", headerName: "Dt recd at PIMO (Courier)" },
    { field: "pimoMumbai.receivedBy", headerName: "Name recd by PIMO (Courier)" },
    { field: "qsMumbai.dateGiven", headerName: "Dt given to QS Mumbai" },
    { field: "qsMumbai.name", headerName: "Name of QS Mumbai" },
    { field: "pimoMumbai.dateGivenPIMO", headerName: "Dt returned back to PIMO by QS Mumbai" },
    { field: "pimoMumbai.namePIMO", headerName: "Name returned back to PIMO by QS Mumbai" },
    { field: "itDept.dateGiven", headerName: "Date given to IT Dept for SES" },
    { field: "itDept.name", headerName: "Name of IT Dept for SES" },
    { field: "pimoMumbai.dateGivenPIMO2", headerName: "Dt given to PIMO for SES" },
    // { field: "pimoMumbai.namePIMO2", headerName: "Name of PIMO for SES" },
    { field: "sesDetails.name", headerName: "Name of PIMO for SES" },
    { field: "sesDetails.no", headerName: "SES no" },
    { field: "sesDetails.amount", headerName: "SES Amt" },
    { field: "sesDetails.dateGiven", headerName: "SES Dt" },
    { field: "sesDetails.doneBy", headerName: "SES done by" },
    { field: "pimoMumbai.dateReceivedFromIT", headerName: "Dt returned back from IT Dept after SES" },
    { field: "pimoMumbai.dateReceivedFromPIMO", headerName: "Dt returned back from PIMO after SES" },
    { field: "approvalDetails.directorApproval.dateGiven", headerName: "Dt given to Director/Advisor/Trustee for approval" },
    { field: "approvalDetails.directorApproval.dateReceived", headerName: "Dt returned back in PIMO after approval" },
    { field: "approvalDetails.remarksPimoMumbai", headerName: "Remarks PIMO Mumbai" },
    { field: "accountsDept.dateGiven", headerName: "Dt given to Accts Dept" },
    { field: "accountsDept.givenBy", headerName: "Name given by PIMO to Accts Dept" },
    { field: "accountsDept.dateReceived", headerName: "Dt recd in Accts Dept" },
    { field: "accountsDept.receivedBy", headerName: "Name recd by Accts Dept" },
    { field: "accountsDept.returnedToPimo", headerName: "Dt returned back to PIMO by Accts Dept" },
    { field: "accountsDept.receivedBack", headerName: "Dt recd back in Accts dept" },
    { field: "accountsDept.invBookingChecking", headerName: "Dt given for booking and checking" },
    { field: "accountsDept.paymentInstructions", headerName: "Payment instructions" },
    { field: "accountsDept.remarksForPayInstructions", headerName: "Remarks for pay instructions" },
    { field: "accountsDept.f110Identification", headerName: "F110 Identification" },
    { field: "accountsDept.paymentDate", headerName: "Dt of Payment" },
    { field: "accountsDept.hardCopy", headerName: "Hard Copy" },
    { field: "accountsDept.accountsIdentification", headerName: "Accts Identification" },
    { field: "accountsDept.paymentAmt", headerName: "Payment Amt" },
    { field: "accountsDept.remarksAcctsDept", headerName: "Remarks Accts Dept" },
    { field: "accountsDept.status", headerName: "Payment Status" },
    { field: "miroDetails.no", headerName: "MIRO no" },
    { field: "miroDetails.date", headerName: "MIRO Dt" },
    { field: "miroDetails.amount", headerName: "MIRO Amt" }
  ];

  const roleSpecificEditFields = {
    SITE_OFFICER: [
      "natureOfWork",
      "region",
      "projectDescription",
      "vendorNo",
      "vendorName",
      "poCreated",
      "poNo",
      "poDate",
      "poAmt",
      "proformaInvNo",
      "proformaInvDate",
      "proformaInvAmt",
      "proformaInvRecdAtSite",
      "proformaInvRecdBy",
      "taxInvNo",
      "taxInvDate",
      "currency",
      "taxInvAmt",
      "taxInvRecdAtSite",
      "taxInvRecdBy",
      "department",
      "remarksBySiteTeam",
      "attachments",
      "qualityEngineer.dateGiven",
      "qualityEngineer.name",
      "qsInspection.dateGiven",
      "qsInspection.name",
      "qsCOP.name",
      "migoDetails.dateGiven",
      "migoDetails.no",
      "migoDetails.date",
      "migoDetails.amount",
      "migoDetails.doneBy",
      "invReturnedToSite",
      "siteEngineer.dateGiven",
      "siteEngineer.name",
      "architect.dateGiven",
      "architect.name",
      "siteIncharge.dateGiven",
      "siteIncharge.name",
      "remarks",
      "siteOfficeDispatch.dateGiven",
      "siteOfficeDispatch.name",
      "siteStatus",
      "pimoMumbai.dateGiven",
      "attachments",
    ],

    QS_TEAM: [
      "qsMeasurementCheck.dateGiven",
      "vendorFinalInv.dateGiven",
      "vendorFinalInv.name",
      "qsCOP.dateGiven",
      "qsCOP.name",
      "copDetails.date",
      "copDetails.amount",
      "remarksByQSTeam",
      "pimoMumbai.dateGivenPIMO",
      "pimoMumbai.namePIMO",
      "attachments",
    ],

    PIMO_MUMBAI_MIGO_SES: [
      "migoDetails.dateGiven",
      "migoDetails.no",
      "migoDetails.date",
      "migoDetails.amount",
      "migoDetails.doneBy",
      "pimoMumbai.dateReceived",
      "pimoMumbai.receivedBy",
      "qsMumbai.dateGiven",
      "qsMumbai.name",
      "pimoMumbai.dateGivenPIMO",
      "itDept.dateGiven",
      "pimoMumbai.dateGivenPIMO2",
      "sesDetails.name",
      "sesDetails.no",
      "sesDetails.amount",
      "sesDetails.dateGiven",
      "sesDetails.doneBy",
      "pimoMumbai.dateReceivedFromIT",
      "pimoMumbai.dateReceivedFromPIMO",
      "approvalDetails.directorApproval.dateReceived",
      "approvalDetails.remarksPimoMumbai",
      "accountsDept.dateGiven",
      "accountsDept.givenBy",
      "attachments",
    ],

    PIMO_MUMBAI_ADVANCE_FI: [
      "natureOfWork",
      "region",
      "projectDescription",
      "vendorNo",
      "vendorName",
      "poCreated",
      "poNo",
      "poDate",
      "poAmt",
      "proformaInvNo",
      "proformaInvDate",
      "proformaInvAmt",
      "taxInvNo",
      "taxInvDate",
      "currency",
      "taxInvAmt",
      "taxInvRecdAtSite",
      "taxInvRecdBy",
      "remarksBySiteTeam",
      "attachments",
      "advanceDate",
      "advanceAmt",
      "advancePercentage",
      "advRequestEnteredBy",
      "qualityEngineer.dateGiven",
      "qualityEngineer.name",
      "qsInspection.dateGiven",
      "qsInspection.name",
      "qsMeasurementCheck.dateGiven",
      "vendorFinalInv.dateGiven",
      "vendorFinalInv.name",
      "qsCOP.dateGiven",
      "qsCOP.name",
      "copDetails.date",
      "copDetails.amount",
      "migoDetails.no",
      "migoDetails.date",
      "migoDetails.amount",
      "migoDetails.doneBy",
      "siteEngineer.dateGiven",
      "siteEngineer.name",
      "architect.dateGiven",
      "architect.name",
      "siteIncharge.dateGiven",
      "siteIncharge.name",
      "remarks",
      "siteOfficeDispatch.dateGiven",
      "siteOfficeDispatch.name",
      "siteStatus",
      "pimoMumbai.dateGiven",
      "pimoMumbai.dateReceived",
      "pimoMumbai.receivedBy",
      "qsMumbai.dateGiven",
      "qsMumbai.name",
      "pimoMumbai.dateGivenPIMO",
      "itDept.dateGiven",
      "pimoMumbai.dateGivenPIMO2",
      "sesDetails.name",
      "sesDetails.no",
      "sesDetails.amount",
      "sesDetails.dateGiven",
      "sesDetails.doneBy",
      "pimoMumbai.dateReceivedFromIT",
      "pimoMumbai.dateReceivedFromPIMO",
      "approvalDetails.directorApproval.dateReceived",
      "approvalDetails.remarksPimoMumbai",
      "accountsDept.dateGiven",
      "accountsDept.givenBy",
      "attachments",
    ],

    ACCOUNTS_TEAM: [
      "accountsDept.dateReceived",
      "accountsDept.receivedBy",
      "accountsDept.returnedToPimo",
      "accountsDept.receivedBack",
      "accountsDept.paymentInstructions",
      "accountsDept.f110Identification",
      "accountsDept.paymentDate",
      "accountsDept.hardCopy",
      "accountsDept.accountsIdentification",
      "accountsDept.paymentAmt",
      "accountsDept.remarksAcctsDept",
      "accountsDept.status",
      "accountsDept.invBookingChecking",
      "attachments",
    ],

    DIRECTOR_TRUSTEE_ADVISOR: [
      "approvalDetails.directorApproval.dateGiven",
      "accountsDept.paymentInstructions",
      "accountsDept.remarksForPayInstructions",
      "attachments",
    ],

    ADMIN: allColumns.map((col) => col.field),
  };

  if (roleSpecificEditFields[role]) {
    return allColumns.filter((column) =>
      roleSpecificEditFields[role].includes(column.field)
    );
  }

  return allColumns.slice(0, 12);
};
